### ISSUE TITLE
b.receive(); is not collecting requested number of samples.

### ISSUE THREAD

**Issue by brute4ss** [JoseAmador95/BladeRF_MIMO#4]
So, I am trying to start with a simple tone pulse at 1GHz for 100ms out of both Tx channels and then receive this tone into both Rx ports. After receiving, I keep getting exactly 125 real samples that I can confirm with an FFT, but 125 to the requested number of samples is padded with zeros. I have tried with and without a 3-second timeout, an appropriate timestamp corresponding to the transmit time, and no transmit at all. I was expecting at least noise for the entire duration of the received signal. Any help would be greatly appreciated! 
Thanks, 
`[y,~,~,overrun] = b.receive(round(NUM_Samples),3000,transmittime);% assign rx1&2 to y. 

pause(.9);% accounted for in 'transmittime'

b.transmit(s,3000,transmittime,true,true);`

**Comment by JoseAmador95** [comment]
I think that you are doing doing the transaction in the wrong order. Transmitting is a non-blocking function, while receiving is. The timeout is only for the synchronous api can start the command within the given lapse, not for setting the listening time.

**Comment by brute4ss** [comment]
![350samples](https://user-images.githubusercontent.com/77061261/175354336-ca983f4c-ea71-4ce1-ae5e-c69192f2c2d0.png)
![400samples](https://user-images.githubusercontent.com/77061261/175354339-011cbdf8-f58e-47d1-90cf-88f4f1907135.png)

I think these plots will help describe my issue. The transmit has been tested and works great. But these plots show that no matter the requested number of samples, I only get (excuse my last 125 number) 250 samples.

**Comment by JoseAmador95** [comment]
Would you please post your script?

**Comment by brute4ss** [comment]
[Blade_Tone_2X2.txt](https://github.com/JoseAmador95/BladeRF_MIMO/files/8969513/Blade_Tone_2X2.txt)
Here is the script I have been using.

**Comment by brute4ss** [comment]
Here is the script I have been using
[Blade_Tone_2X2.txt](https://github.com/JoseAmador95/BladeRF_MIMO/files/8969565/Blade_Tone_2X2.txt)
.

**Comment by brute4ss** [comment]
I am using the most current version of MATLAB. Maybe this could be a part of the issue?

**Comment by JoseAmador95** [comment]
Some of my thoughts
* Are you dropping samples? If `overrun` is true at the end of the script, then you are missing samples. That would be not ideal at all.
* The sample rate (`fs = 10e6`) seems too high. In my experience, 1e6 was the sweetspot when using the simulink blocks. Anything higher would cause dropped samples.
* I think I have missed to disclose this in my documentation, but I've found that the latest version of the BladeRF firmware (2021.02) had issues with Matlab. I used 2019.07 for my work. This may be IT.
* Again, I see no reason to call `receive` before `transmit`. The way it is done in the simulink blocks is Tx first and then Rx. This method has proven to work, even when considering the start timestamp (`transmittime`).

**Comment by JoseAmador95** [comment]
You should try to run my [hardware demo](https://github.com/JoseAmador95/UoS_Beamforming/blob/master/Real_Implementation/test_sdr_mimo.slx) it should run out-of-the-box (or at least with comprehensible issues).

**Comment by brute4ss** [comment]
Thank You! I will look into these considerations. You have been extremely helpful!

**Comment by JoseAmador95** [comment]
No worries. I'll leave this issue open in case you still need assistance. Please, if you get something worth sharing (i.e., a working example script, improved documentation) do not hesitate to raise a Pull Request. I'd like this project to be maintained, but I lost access to the hardware a while ago.
